/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AuthRouteRouteImport } from './../routes/_auth/route'
import { Route as PublicRouteRouteImport } from './../routes/_public/route'
import { Route as ConsoleRouteRouteImport } from './../routes/console/route'
import { Route as AuthChangePasswordRouteImport } from './../routes/_auth/change-password'
import { Route as AuthResetPasswordRouteImport } from './../routes/_auth/reset-password'
import { Route as AuthSigninRouteImport } from './../routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './../routes/_auth/signup'
import { Route as AuthTwoFactorRouteRouteImport } from './../routes/_auth/two-factor/route'
import { Route as AuthVerifyResetRouteImport } from './../routes/_auth/verify-reset'
import { Route as AuthVerifySignupRouteImport } from './../routes/_auth/verify-signup'
import { Route as PublicIndexRouteImport } from './../routes/_public/index'
import { Route as ConsoleIndexRouteImport } from './../routes/console/index'
import { Route as AuthTwoFactorIndexRouteImport } from './../routes/_auth/two-factor/index'
import { Route as AuthTwoFactorAppRouteImport } from './../routes/_auth/two-factor/app'
import { Route as AuthTwoFactorRecoveryRouteImport } from './../routes/_auth/two-factor/recovery'
import { Route as AuthTwoFactorWebauthnRouteImport } from './../routes/_auth/two-factor/webauthn'
import { Route as PublicLegalIndexRouteImport } from './../routes/_public/legal/index'
import { Route as PublicLegalPrivacyPoliceRouteImport } from './../routes/_public/legal/privacy-police'
import { Route as PublicLegalTermsOfServiceRouteImport } from './../routes/_public/legal/terms-of-service'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorRouteRoute = AuthTwoFactorRouteRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyResetRoute = AuthVerifyResetRouteImport.update({
  id: '/verify-reset',
  path: '/verify-reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifySignupRoute = AuthVerifySignupRouteImport.update({
  id: '/verify-signup',
  path: '/verify-signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTwoFactorRouteRoute,
} as any)
const AuthTwoFactorAppRoute = AuthTwoFactorAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthTwoFactorRouteRoute,
} as any)
const AuthTwoFactorRecoveryRoute = AuthTwoFactorRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthTwoFactorRouteRoute,
} as any)
const AuthTwoFactorWebauthnRoute = AuthTwoFactorWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AuthTwoFactorRouteRoute,
} as any)
const PublicLegalIndexRoute = PublicLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLegalPrivacyPoliceRoute =
  PublicLegalPrivacyPoliceRouteImport.update({
    id: '/legal/privacy-police',
    path: '/legal/privacy-police',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicLegalTermsOfServiceRoute =
  PublicLegalTermsOfServiceRouteImport.update({
    id: '/legal/terms-of-service',
    path: '/legal/terms-of-service',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/two-factor': typeof AuthTwoFactorRouteRouteWithChildren
  '/change-password': typeof AuthChangePasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-reset': typeof AuthVerifyResetRoute
  '/verify-signup': typeof AuthVerifySignupRoute
  '/console/': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/two-factor/': typeof AuthTwoFactorIndexRoute
  '/legal/': typeof PublicLegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-reset': typeof AuthVerifyResetRoute
  '/verify-signup': typeof AuthVerifySignupRoute
  '/console': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/two-factor': typeof AuthTwoFactorIndexRoute
  '/legal': typeof PublicLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/_auth/two-factor': typeof AuthTwoFactorRouteRouteWithChildren
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-reset': typeof AuthVerifyResetRoute
  '/_auth/verify-signup': typeof AuthVerifySignupRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/_auth/two-factor/app': typeof AuthTwoFactorAppRoute
  '/_auth/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/_auth/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/_public/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/_public/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/_auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/_public/legal/': typeof PublicLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/two-factor'
    | '/change-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-reset'
    | '/verify-signup'
    | '/console/'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/two-factor/webauthn'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/two-factor/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-reset'
    | '/verify-signup'
    | '/console'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/two-factor/webauthn'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/two-factor'
    | '/legal'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/console'
    | '/_auth/two-factor'
    | '/_auth/change-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-reset'
    | '/_auth/verify-signup'
    | '/_public/'
    | '/console/'
    | '/_auth/two-factor/app'
    | '/_auth/two-factor/recovery'
    | '/_auth/two-factor/webauthn'
    | '/_public/legal/privacy-police'
    | '/_public/legal/terms-of-service'
    | '/_auth/two-factor/'
    | '/_public/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-reset': {
      id: '/_auth/verify-reset'
      path: '/verify-reset'
      fullPath: '/verify-reset'
      preLoaderRoute: typeof AuthVerifyResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify-signup': {
      id: '/_auth/verify-signup'
      path: '/verify-signup'
      fullPath: '/verify-signup'
      preLoaderRoute: typeof AuthVerifySignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_auth/two-factor/': {
      id: '/_auth/two-factor/'
      path: '/'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthTwoFactorRouteRoute
    }
    '/_auth/two-factor/app': {
      id: '/_auth/two-factor/app'
      path: '/app'
      fullPath: '/two-factor/app'
      preLoaderRoute: typeof AuthTwoFactorAppRouteImport
      parentRoute: typeof AuthTwoFactorRouteRoute
    }
    '/_auth/two-factor/recovery': {
      id: '/_auth/two-factor/recovery'
      path: '/recovery'
      fullPath: '/two-factor/recovery'
      preLoaderRoute: typeof AuthTwoFactorRecoveryRouteImport
      parentRoute: typeof AuthTwoFactorRouteRoute
    }
    '/_auth/two-factor/webauthn': {
      id: '/_auth/two-factor/webauthn'
      path: '/webauthn'
      fullPath: '/two-factor/webauthn'
      preLoaderRoute: typeof AuthTwoFactorWebauthnRouteImport
      parentRoute: typeof AuthTwoFactorRouteRoute
    }
    '/_public/legal/': {
      id: '/_public/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof PublicLegalIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/privacy-police': {
      id: '/_public/legal/privacy-police'
      path: '/legal/privacy-police'
      fullPath: '/legal/privacy-police'
      preLoaderRoute: typeof PublicLegalPrivacyPoliceRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/terms-of-service': {
      id: '/_public/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof PublicLegalTermsOfServiceRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface AuthTwoFactorRouteRouteChildren {
  AuthTwoFactorAppRoute: typeof AuthTwoFactorAppRoute
  AuthTwoFactorRecoveryRoute: typeof AuthTwoFactorRecoveryRoute
  AuthTwoFactorWebauthnRoute: typeof AuthTwoFactorWebauthnRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
}

const AuthTwoFactorRouteRouteChildren: AuthTwoFactorRouteRouteChildren = {
  AuthTwoFactorAppRoute: AuthTwoFactorAppRoute,
  AuthTwoFactorRecoveryRoute: AuthTwoFactorRecoveryRoute,
  AuthTwoFactorWebauthnRoute: AuthTwoFactorWebauthnRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
}

const AuthTwoFactorRouteRouteWithChildren =
  AuthTwoFactorRouteRoute._addFileChildren(AuthTwoFactorRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthTwoFactorRouteRoute: typeof AuthTwoFactorRouteRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyResetRoute: typeof AuthVerifyResetRoute
  AuthVerifySignupRoute: typeof AuthVerifySignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthTwoFactorRouteRoute: AuthTwoFactorRouteRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyResetRoute: AuthVerifyResetRoute,
  AuthVerifySignupRoute: AuthVerifySignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicLegalPrivacyPoliceRoute: typeof PublicLegalPrivacyPoliceRoute
  PublicLegalTermsOfServiceRoute: typeof PublicLegalTermsOfServiceRoute
  PublicLegalIndexRoute: typeof PublicLegalIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicLegalPrivacyPoliceRoute: PublicLegalPrivacyPoliceRoute,
  PublicLegalTermsOfServiceRoute: PublicLegalTermsOfServiceRoute,
  PublicLegalIndexRoute: PublicLegalIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
