/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AuthRouteImport } from './../routes/_auth'
import { Route as PublicRouteImport } from './../routes/_public'
import { Route as ConsoleRouteImport } from './../routes/console'
import { Route as AuthChangePasswordRouteImport } from './../routes/_auth.change-password'
import { Route as AuthResetPasswordRouteImport } from './../routes/_auth.reset-password'
import { Route as AuthSigninRouteImport } from './../routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './../routes/_auth.signup'
import { Route as AuthTwoFactorRouteImport } from './../routes/_auth.two-factor'
import { Route as AuthVerifyResetRouteImport } from './../routes/_auth.verify-reset'
import { Route as AuthVerifySignupRouteImport } from './../routes/_auth.verify-signup'
import { Route as PublicIndexRouteImport } from './../routes/_public.index'
import { Route as ConsoleIndexRouteImport } from './../routes/console.index'
import { Route as AuthTwoFactorIndexRouteImport } from './../routes/_auth.two-factor.index'
import { Route as AuthTwoFactorAppRouteImport } from './../routes/_auth.two-factor.app'
import { Route as AuthTwoFactorRecoveryRouteImport } from './../routes/_auth.two-factor.recovery'
import { Route as AuthTwoFactorWebauthnRouteImport } from './../routes/_auth.two-factor.webauthn'
import { Route as PublicLegalIndexRouteImport } from './../routes/_public.legal.index'
import { Route as PublicLegalPrivacyPoliceRouteImport } from './../routes/_public.legal.privacy-police'
import { Route as PublicLegalTermsOfServiceRouteImport } from './../routes/_public.legal.terms-of-service'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyResetRoute = AuthVerifyResetRouteImport.update({
  id: '/verify-reset',
  path: '/verify-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifySignupRoute = AuthVerifySignupRouteImport.update({
  id: '/verify-signup',
  path: '/verify-signup',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTwoFactorRoute,
} as any)
const AuthTwoFactorAppRoute = AuthTwoFactorAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthTwoFactorRoute,
} as any)
const AuthTwoFactorRecoveryRoute = AuthTwoFactorRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthTwoFactorRoute,
} as any)
const AuthTwoFactorWebauthnRoute = AuthTwoFactorWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AuthTwoFactorRoute,
} as any)
const PublicLegalIndexRoute = PublicLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalPrivacyPoliceRoute =
  PublicLegalPrivacyPoliceRouteImport.update({
    id: '/legal/privacy-police',
    path: '/legal/privacy-police',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicLegalTermsOfServiceRoute =
  PublicLegalTermsOfServiceRouteImport.update({
    id: '/legal/terms-of-service',
    path: '/legal/terms-of-service',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/change-password': typeof AuthChangePasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/two-factor': typeof AuthTwoFactorRouteWithChildren
  '/verify-reset': typeof AuthVerifyResetRoute
  '/verify-signup': typeof AuthVerifySignupRoute
  '/console/': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/two-factor/': typeof AuthTwoFactorIndexRoute
  '/legal/': typeof PublicLegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-reset': typeof AuthVerifyResetRoute
  '/verify-signup': typeof AuthVerifySignupRoute
  '/console': typeof ConsoleIndexRoute
  '/two-factor/app': typeof AuthTwoFactorAppRoute
  '/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/two-factor': typeof AuthTwoFactorIndexRoute
  '/legal': typeof PublicLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/two-factor': typeof AuthTwoFactorRouteWithChildren
  '/_auth/verify-reset': typeof AuthVerifyResetRoute
  '/_auth/verify-signup': typeof AuthVerifySignupRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/_auth/two-factor/app': typeof AuthTwoFactorAppRoute
  '/_auth/two-factor/recovery': typeof AuthTwoFactorRecoveryRoute
  '/_auth/two-factor/webauthn': typeof AuthTwoFactorWebauthnRoute
  '/_public/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/_public/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/_auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/_public/legal/': typeof PublicLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/change-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/two-factor'
    | '/verify-reset'
    | '/verify-signup'
    | '/console/'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/two-factor/webauthn'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/two-factor/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-reset'
    | '/verify-signup'
    | '/console'
    | '/two-factor/app'
    | '/two-factor/recovery'
    | '/two-factor/webauthn'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/two-factor'
    | '/legal'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/console'
    | '/_auth/change-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/two-factor'
    | '/_auth/verify-reset'
    | '/_auth/verify-signup'
    | '/_public/'
    | '/console/'
    | '/_auth/two-factor/app'
    | '/_auth/two-factor/recovery'
    | '/_auth/two-factor/webauthn'
    | '/_public/legal/privacy-police'
    | '/_public/legal/terms-of-service'
    | '/_auth/two-factor/'
    | '/_public/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-reset': {
      id: '/_auth/verify-reset'
      path: '/verify-reset'
      fullPath: '/verify-reset'
      preLoaderRoute: typeof AuthVerifyResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-signup': {
      id: '/_auth/verify-signup'
      path: '/verify-signup'
      fullPath: '/verify-signup'
      preLoaderRoute: typeof AuthVerifySignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_auth/two-factor/': {
      id: '/_auth/two-factor/'
      path: '/'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthTwoFactorRoute
    }
    '/_auth/two-factor/app': {
      id: '/_auth/two-factor/app'
      path: '/app'
      fullPath: '/two-factor/app'
      preLoaderRoute: typeof AuthTwoFactorAppRouteImport
      parentRoute: typeof AuthTwoFactorRoute
    }
    '/_auth/two-factor/recovery': {
      id: '/_auth/two-factor/recovery'
      path: '/recovery'
      fullPath: '/two-factor/recovery'
      preLoaderRoute: typeof AuthTwoFactorRecoveryRouteImport
      parentRoute: typeof AuthTwoFactorRoute
    }
    '/_auth/two-factor/webauthn': {
      id: '/_auth/two-factor/webauthn'
      path: '/webauthn'
      fullPath: '/two-factor/webauthn'
      preLoaderRoute: typeof AuthTwoFactorWebauthnRouteImport
      parentRoute: typeof AuthTwoFactorRoute
    }
    '/_public/legal/': {
      id: '/_public/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof PublicLegalIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/privacy-police': {
      id: '/_public/legal/privacy-police'
      path: '/legal/privacy-police'
      fullPath: '/legal/privacy-police'
      preLoaderRoute: typeof PublicLegalPrivacyPoliceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/terms-of-service': {
      id: '/_public/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof PublicLegalTermsOfServiceRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthTwoFactorRouteChildren {
  AuthTwoFactorAppRoute: typeof AuthTwoFactorAppRoute
  AuthTwoFactorRecoveryRoute: typeof AuthTwoFactorRecoveryRoute
  AuthTwoFactorWebauthnRoute: typeof AuthTwoFactorWebauthnRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
}

const AuthTwoFactorRouteChildren: AuthTwoFactorRouteChildren = {
  AuthTwoFactorAppRoute: AuthTwoFactorAppRoute,
  AuthTwoFactorRecoveryRoute: AuthTwoFactorRecoveryRoute,
  AuthTwoFactorWebauthnRoute: AuthTwoFactorWebauthnRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
}

const AuthTwoFactorRouteWithChildren = AuthTwoFactorRoute._addFileChildren(
  AuthTwoFactorRouteChildren,
)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRouteWithChildren
  AuthVerifyResetRoute: typeof AuthVerifyResetRoute
  AuthVerifySignupRoute: typeof AuthVerifySignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthTwoFactorRoute: AuthTwoFactorRouteWithChildren,
  AuthVerifyResetRoute: AuthVerifyResetRoute,
  AuthVerifySignupRoute: AuthVerifySignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicLegalPrivacyPoliceRoute: typeof PublicLegalPrivacyPoliceRoute
  PublicLegalTermsOfServiceRoute: typeof PublicLegalTermsOfServiceRoute
  PublicLegalIndexRoute: typeof PublicLegalIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicLegalPrivacyPoliceRoute: PublicLegalPrivacyPoliceRoute,
  PublicLegalTermsOfServiceRoute: PublicLegalTermsOfServiceRoute,
  PublicLegalIndexRoute: PublicLegalIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
