/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AuthRouteRouteImport } from './../routes/_auth/route'
import { Route as PublicRouteRouteImport } from './../routes/_public/route'
import { Route as AuthResetPasswordRouteImport } from './../routes/_auth/reset-password'
import { Route as AuthSigninRouteImport } from './../routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './../routes/_auth/signup'
import { Route as PublicIndexRouteImport } from './../routes/_public/index'
import { Route as PublicLegalRouteRouteImport } from './../routes/_public/legal/route'
import { Route as SessionsTwoFactorRouteRouteImport } from './../routes/sessions/two-factor/route'
import { Route as PublicLegalIndexRouteImport } from './../routes/_public/legal/index'
import { Route as PublicLegalPrivacyPoliceRouteImport } from './../routes/_public/legal/privacy-police'
import { Route as PublicLegalTermsOfServiceRouteImport } from './../routes/_public/legal/terms-of-service'
import { Route as SessionsTwoFactorAppRouteImport } from './../routes/sessions/two-factor/app'
import { Route as SessionsTwoFactorRecoveryRouteImport } from './../routes/sessions/two-factor/recovery'
import { Route as SessionsTwoFactorWebauthnRouteImport } from './../routes/sessions/two-factor/webauthn'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLegalRouteRoute = PublicLegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => PublicRouteRoute,
} as any)
const SessionsTwoFactorRouteRoute = SessionsTwoFactorRouteRouteImport.update({
  id: '/sessions/two-factor',
  path: '/sessions/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLegalIndexRoute = PublicLegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLegalRouteRoute,
} as any)
const PublicLegalPrivacyPoliceRoute =
  PublicLegalPrivacyPoliceRouteImport.update({
    id: '/privacy-police',
    path: '/privacy-police',
    getParentRoute: () => PublicLegalRouteRoute,
  } as any)
const PublicLegalTermsOfServiceRoute =
  PublicLegalTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => PublicLegalRouteRoute,
  } as any)
const SessionsTwoFactorAppRoute = SessionsTwoFactorAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => SessionsTwoFactorRouteRoute,
} as any)
const SessionsTwoFactorRecoveryRoute =
  SessionsTwoFactorRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => SessionsTwoFactorRouteRoute,
  } as any)
const SessionsTwoFactorWebauthnRoute =
  SessionsTwoFactorWebauthnRouteImport.update({
    id: '/webauthn',
    path: '/webauthn',
    getParentRoute: () => SessionsTwoFactorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/legal': typeof PublicLegalRouteRouteWithChildren
  '/sessions/two-factor': typeof SessionsTwoFactorRouteRouteWithChildren
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/sessions/two-factor/recovery': typeof SessionsTwoFactorRecoveryRoute
  '/sessions/two-factor/webauthn': typeof SessionsTwoFactorWebauthnRoute
  '/legal/': typeof PublicLegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/sessions/two-factor': typeof SessionsTwoFactorRouteRouteWithChildren
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/sessions/two-factor/recovery': typeof SessionsTwoFactorRecoveryRoute
  '/sessions/two-factor/webauthn': typeof SessionsTwoFactorWebauthnRoute
  '/legal': typeof PublicLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/legal': typeof PublicLegalRouteRouteWithChildren
  '/sessions/two-factor': typeof SessionsTwoFactorRouteRouteWithChildren
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/legal/privacy-police': typeof PublicLegalPrivacyPoliceRoute
  '/_public/legal/terms-of-service': typeof PublicLegalTermsOfServiceRoute
  '/sessions/two-factor/app': typeof SessionsTwoFactorAppRoute
  '/sessions/two-factor/recovery': typeof SessionsTwoFactorRecoveryRoute
  '/sessions/two-factor/webauthn': typeof SessionsTwoFactorWebauthnRoute
  '/_public/legal/': typeof PublicLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/sessions/two-factor'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/sessions/two-factor/app'
    | '/sessions/two-factor/recovery'
    | '/sessions/two-factor/webauthn'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/two-factor'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/legal/privacy-police'
    | '/legal/terms-of-service'
    | '/sessions/two-factor/app'
    | '/sessions/two-factor/recovery'
    | '/sessions/two-factor/webauthn'
    | '/legal'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_public/legal'
    | '/sessions/two-factor'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_public/'
    | '/_public/legal/privacy-police'
    | '/_public/legal/terms-of-service'
    | '/sessions/two-factor/app'
    | '/sessions/two-factor/recovery'
    | '/sessions/two-factor/webauthn'
    | '/_public/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SessionsTwoFactorRouteRoute: typeof SessionsTwoFactorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal': {
      id: '/_public/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PublicLegalRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/sessions/two-factor': {
      id: '/sessions/two-factor'
      path: '/sessions/two-factor'
      fullPath: '/sessions/two-factor'
      preLoaderRoute: typeof SessionsTwoFactorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/legal/': {
      id: '/_public/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof PublicLegalIndexRouteImport
      parentRoute: typeof PublicLegalRouteRoute
    }
    '/_public/legal/privacy-police': {
      id: '/_public/legal/privacy-police'
      path: '/privacy-police'
      fullPath: '/legal/privacy-police'
      preLoaderRoute: typeof PublicLegalPrivacyPoliceRouteImport
      parentRoute: typeof PublicLegalRouteRoute
    }
    '/_public/legal/terms-of-service': {
      id: '/_public/legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof PublicLegalTermsOfServiceRouteImport
      parentRoute: typeof PublicLegalRouteRoute
    }
    '/sessions/two-factor/app': {
      id: '/sessions/two-factor/app'
      path: '/app'
      fullPath: '/sessions/two-factor/app'
      preLoaderRoute: typeof SessionsTwoFactorAppRouteImport
      parentRoute: typeof SessionsTwoFactorRouteRoute
    }
    '/sessions/two-factor/recovery': {
      id: '/sessions/two-factor/recovery'
      path: '/recovery'
      fullPath: '/sessions/two-factor/recovery'
      preLoaderRoute: typeof SessionsTwoFactorRecoveryRouteImport
      parentRoute: typeof SessionsTwoFactorRouteRoute
    }
    '/sessions/two-factor/webauthn': {
      id: '/sessions/two-factor/webauthn'
      path: '/webauthn'
      fullPath: '/sessions/two-factor/webauthn'
      preLoaderRoute: typeof SessionsTwoFactorWebauthnRouteImport
      parentRoute: typeof SessionsTwoFactorRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicLegalRouteRouteChildren {
  PublicLegalPrivacyPoliceRoute: typeof PublicLegalPrivacyPoliceRoute
  PublicLegalTermsOfServiceRoute: typeof PublicLegalTermsOfServiceRoute
  PublicLegalIndexRoute: typeof PublicLegalIndexRoute
}

const PublicLegalRouteRouteChildren: PublicLegalRouteRouteChildren = {
  PublicLegalPrivacyPoliceRoute: PublicLegalPrivacyPoliceRoute,
  PublicLegalTermsOfServiceRoute: PublicLegalTermsOfServiceRoute,
  PublicLegalIndexRoute: PublicLegalIndexRoute,
}

const PublicLegalRouteRouteWithChildren =
  PublicLegalRouteRoute._addFileChildren(PublicLegalRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLegalRouteRoute: typeof PublicLegalRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLegalRouteRoute: PublicLegalRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface SessionsTwoFactorRouteRouteChildren {
  SessionsTwoFactorAppRoute: typeof SessionsTwoFactorAppRoute
  SessionsTwoFactorRecoveryRoute: typeof SessionsTwoFactorRecoveryRoute
  SessionsTwoFactorWebauthnRoute: typeof SessionsTwoFactorWebauthnRoute
}

const SessionsTwoFactorRouteRouteChildren: SessionsTwoFactorRouteRouteChildren =
  {
    SessionsTwoFactorAppRoute: SessionsTwoFactorAppRoute,
    SessionsTwoFactorRecoveryRoute: SessionsTwoFactorRecoveryRoute,
    SessionsTwoFactorWebauthnRoute: SessionsTwoFactorWebauthnRoute,
  }

const SessionsTwoFactorRouteRouteWithChildren =
  SessionsTwoFactorRouteRoute._addFileChildren(
    SessionsTwoFactorRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SessionsTwoFactorRouteRoute: SessionsTwoFactorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
